"""Add ApiKey model for API key management

Revision ID: 079bc57431b3
Revises: 801929404db6
Create Date: 2025-09-06 09:12:22.244188

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "079bc57431b3"
down_revision = "801929404db6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_key_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_api_key_key"), ["key"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_api_key_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_key_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_key_key"))
        batch_op.drop_index(batch_op.f("ix_api_key_created_at"))

    op.drop_table("api_key")
    # ### end Alembic commands ###
