"""BatchFormula table added.

Revision ID: 22a461fb2313
Revises: 74e5386cbde1
Create Date: 2024-06-01 20:53:27.165600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a461fb2313'
down_revision = '74e5386cbde1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_formula', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_formula_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_formula_ingredient_id'), ['ingredient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_formula', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_formula_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_batch_formula_batch_id'))

    op.drop_table('batch_formula')
    # ### end Alembic commands ###
