"""New indexes

Revision ID: 53a44446cf4d
Revises: c6111a50522d
Create Date: 2025-08-02 21:11:01.910096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a44446cf4d'
down_revision = 'c6111a50522d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.alter_column('bottle_volume_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text('("ml")'))
        batch_op.create_index('idx_batch_liquor_date', ['liquor_id', 'date'], unique=False)

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_ingredient_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_created_at'))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_index('idx_batch_liquor_date')
        batch_op.alter_column('bottle_volume_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text('("ml")'))

    # ### end Alembic commands ###
