"""Ingrediens and Batch tables added

Revision ID: 74e5386cbde1
Revises: 996d308d30b0
Create Date: 2024-05-19 21:35:26.111070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e5386cbde1'
down_revision = '996d308d30b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_name'), ['name'], unique=True)

    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('liquor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['liquor_id'], ['liquor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_liquor_id'), ['liquor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_liquor_id'))
        batch_op.drop_index(batch_op.f('ix_batch_date'))

    op.drop_table('batch')
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_name'))

    op.drop_table('ingredient')
    # ### end Alembic commands ###
