"""updated relationship in user

Revision ID: f29f222d5976
Revises: 
Create Date: 2025-08-07 13:44:57.969612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29f222d5976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('liquor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liquor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquor_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquor_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquor_user_id'), ['user_id'], unique=False)

    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('liquor_id', sa.Integer(), nullable=False),
    sa.Column('bottle_count', sa.Integer(), nullable=True),
    sa.Column('bottle_volume', sa.Float(), nullable=True),
    sa.Column('bottle_volume_unit', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['liquor_id'], ['liquor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.create_index('idx_batch_liquor_date', ['liquor_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_liquor_id'), ['liquor_id'], unique=False)

    op.create_table('batch_formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_formula', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_formula_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_formula_ingredient_id'), ['ingredient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_formula', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_formula_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_batch_formula_batch_id'))

    op.drop_table('batch_formula')
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_liquor_id'))
        batch_op.drop_index(batch_op.f('ix_batch_date'))
        batch_op.drop_index('idx_batch_liquor_date')

    op.drop_table('batch')
    with op.batch_alter_table('liquor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liquor_user_id'))
        batch_op.drop_index(batch_op.f('ix_liquor_name'))
        batch_op.drop_index(batch_op.f('ix_liquor_created'))

    op.drop_table('liquor')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_name'))
        batch_op.drop_index(batch_op.f('ix_ingredient_created_at'))

    op.drop_table('ingredient')
    # ### end Alembic commands ###
